Add retry mechanism for one-phase commit.
We've seen scenario that one-phase fails with error but could or should retry
to succeed.  Typically if error happens at SyncRepWaitForLSN() on QE, the
transaction has been committed locally so we can not error out on QD thus need
to retry to finish that to ensure data consistency.

The bad case example is as below.

postgres=\# insert into t1 values(2);
WARNING:  canceling the wait for synchronous replication and terminating connection due to administrator command  (seg0 192.168.235.128:7002 pid=17340)
DETAIL:  If this happens on QE, connection will be terminated for 1PC/2PC retry.
ERROR:  Error on receive from seg0 192.168.235.128:7002 pid=17340: server closed the connection unexpectedly (cdbdispatchresult.c:476)
DETAIL:
    This probably means the server terminated abnormally